compass_viewer/array/plot.py

Fix the plot title so that it doesn't say "line plot" for contour plots.

fix title for plot

---

filesystem_model/__init__.py

py3k: Use new-style exception handling.

---

hdf_compass/compass_viewer/frame.py

https://github.com/HDFGroup/hdf-compass/pull/50

Fix for the file history bug

---

hdf_compass/compass_viewer/__init__.py
hdf_compass/compass_viewer/frame.py

Enables resources (e.g. OPeNDAP URL) to be added to Open Recent menu

URL support for Open Recent menu update to #50

---

setup.py2app.py

https://github.com/HDFGroup/hdf-compass/pull/86

Fix and rename for setup.py for p2app

---

hdf_compass/bag_model/test.py
hdf_compass/hdf5_model/model.py
hdf_compass/hdf5_model/test.py

Add tests to `bag_model`: https://github.com/HDFGroup/hdf-compass/issues/80
fix `__init__.py` for `hdf5_model`: https://github.com/HDFGroup/hdf-compass/issues/67

Add tests to bag_model + fix __init__ for hdf5_model

---

hdf_compass/hdf5_model/model.py
hdf_compass/opendap_model/model.py

Fix to https://github.com/HDFGroup/hdf-compass/pull/64

Minor changes to add the same can_handle logging for all models

---

README.md
hdf_compass/compass_viewer/frame.py

Related to: https://github.com/HDFGroup/hdf-compass/issues/76

Add 'Online manual' menu item to 'Help' menu

---

hdf_compass/compass_viewer/viewer.py

Some useful debug info: https://github.com/HDFGroup/hdf-compass/issues/60

Add environment info as logging messages

---

data/hdf5/Download/download_data.py

add import exception handling for hdf5 data download (since wget is not a Python standard lib)

Add exception handler for hdf5 data download

---

hdf_compass/array_model/model.py
hdf_compass/bag_model/model.py
hdf_compass/compass_model/model.py
hdf_compass/compass_viewer/array/frame.py
hdf_compass/compass_viewer/frame.py
hdf_compass/compass_viewer/info.py
hdf_compass/hdf5_model/model.py
hdf_compass/opendap_model/model.py

This implement a fix to: https://github.com/HDFGroup/hdf-compass/issues/70:
* Add ``is_plottable`` method to ``Array`` nodes
* Use the new method for ``Array`` classes in ``opendap_model``, ``hdf5_model``, ``array_model``, ``bag_model``

Add is_plottable method for Array node and disabling for string

---

hdf_compass/array_model/model.py
hdf_compass/hdf5_model/model.py
hdf_compass/opendap_model/model.py

Related to https://github.com/HDFGroup/hdf-compass/issues/69
Implement ``Text``-derived node for ``HDF5_model``

Display string dataset in HDF5_model

---

hdf_compass/compass_viewer/container/frame.py

Introduced the accelerator table required by a Mac issue explained here: https://github.com/HDFGroup/hdf-compass/issues/101

Ticket 101

---

hdf_compass/compass_viewer/info.py

Display attribute count in info pane (fix for #74)

display attribute count

---

hdf_compass/compass_viewer/array/plot.py
hdf_compass/compass_viewer/frame.py

- fix the hanging described here https://github.com/HDFGroup/hdf-compass/issues/135 by adding a proper binding (using ``wx,EVT_CLOSE``) and counting the open frames
- add colormap menu items for array plot as proposed here: https://github.com/HDFGroup/hdf-compass/issues/136

Fix close events and add colormaps

---

hdf_compass/compass_viewer/array/plot.py

explained in https://github.com/HDFGroup/hdf-compass/issues/142

add a colorbar to the ContourPlotFrame

---

hdf_compass/compass_viewer/frame.py

New attempt to fix https://github.com/HDFGroup/hdf-compass/issues/140

Ticket 140

---

README.rst
hdf_compass/compass_viewer/frame.py

* always close the app on wx.ID_EXIT
* unify "Close Window" and close [x] frame

close app on ID_EXIT (always) and EVT_CLOSE (only from InitFrame)

---

hdf_compass/compass_viewer/array/plot.py

Explained in PR https://github.com/HDFGroup/hdf-compass/issues/144

Add info under the mouse cursor to array plot

---

hdf_compass/bag_model/model.py
hdf_compass/compass_viewer/geo_array/plot.py
hdf_compass/compass_viewer/geo_surface/plot.py

This PR makes `cartopy` dependency optional

Cartopy optional

---

hdf_compass/opendap_model/model.py

fix the release obstacle described in https://github.com/HDFGroup/hdf-compass/issues/160

bug fix for pydap plugin

---

MANIFEST.in
README.rst
setup.cfg
spec.json

https://github.com/HDFGroup/hdf-compass/issues/160

Changes for sdist on PyPi
